import { expect, test } from "@playwright/test";
test("child routes are independently served",async({page})=>{for(const path of ["/","/study","/finish","/words","/mistakes","/badges","/teacher"]){await page.goto(path);await expect(page.getByRole("heading").first()).toBeVisible();const html=await page.content();expect(html).not.toContain("kimi-english-learning-publish_Copy");}});
test("start today creates a persistent child session", async ({ page }) => { await page.goto("/"); await page.waitForTimeout(150); await page.evaluate(async () => { const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open("kimi-word-adventure"); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); const tx = db.transaction(["progress", "attempts", "sessions", "analytics"], "readwrite"); for (const name of ["progress", "attempts", "sessions", "analytics"]) tx.objectStore(name).clear(); await new Promise<void>((resolve, reject) => { tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }); await page.reload(); await page.getByRole("button", { name: "START TODAY" }).click(); await expect(page.locator(".progress-track")).toBeVisible(); await page.reload(); await expect(page.locator(".progress-track")).toBeVisible(); });
test("primary child controls remain tappable at target viewports", async ({ page }) => { for (const viewport of [{ width: 393, height: 852 }, { width: 375, height: 667 }, { width: 430, height: 932 }, { width: 320, height: 568 }, { width: 1440, height: 900 }]) { await page.setViewportSize(viewport); await page.goto("/"); const button = page.getByRole("button", { name: /START TODAY|PRACTICE AGAIN/ }); await expect(button).toBeVisible(); expect((await button.boundingBox())?.height).toBeGreaterThanOrEqual(60); } });
test("teacher data can be read from the hidden teacher route", async ({ page }) => { await page.goto("/teacher"); await expect(page.getByRole("heading", { name: "Teacher" })).toBeVisible(); await expect(page.getByRole("heading", { name: "Weak Words" })).toBeVisible(); await expect(page.getByRole("heading", { name: "Recent 7 Days" })).toBeVisible(); });
test("an empty profile can complete, refresh, and retain one daily adventure", async ({ page }) => {
  test.setTimeout(60_000); await page.goto("/"); await page.waitForTimeout(150);
  await page.evaluate(async () => { const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open("kimi-word-adventure"); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); const tx = db.transaction(["progress", "attempts", "sessions", "analytics"], "readwrite"); for (const name of ["progress", "attempts", "sessions", "analytics"]) tx.objectStore(name).clear(); await new Promise<void>((resolve, reject) => { tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); });
  await page.reload(); await page.getByRole("button", { name: "START TODAY" }).click(); await expect(page.locator(".progress-track")).toBeVisible(); let madeMistake = false;
  for (let guard = 0; guard < 80; guard++) {
    const state = await page.evaluate(async () => { const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open("kimi-word-adventure"); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); const tx = db.transaction("sessions", "readonly"); const request = tx.objectStore("sessions").getAll(); const sessions = await new Promise<any[]>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); db.close(); const session = sessions[0]; return { completed: Boolean(session?.completedAt), item: session?.interactions?.[session?.currentInteractionIndex ?? 0] }; });
    if (state.completed) break;
    if (!state.item) { await page.waitForTimeout(100); continue; }
    if (state.item.kind === "learn") { await page.getByRole("button", { name: "NEXT" }).click(); continue; }
    const answers = page.locator(".image-answer, .word-answer");
    const choice = madeMistake ? state.item.correctOptionIndex : (state.item.correctOptionIndex + 1) % state.item.options.length;
    await answers.nth(choice).click(); await page.waitForTimeout(madeMistake ? 350 : 300);
    if (!madeMistake) { await answers.nth(choice).click(); await page.waitForTimeout(350); madeMistake = true; }
  }
  await expect(page.getByRole("heading", { name: "Great Job!" })).toBeVisible(); await page.getByRole("button", { name: "DONE" }).click(); await page.reload(); await expect(page.getByText("TODAY’S ADVENTURE COMPLETE")).toBeVisible();
  await page.getByRole("button", { name: "Mistake Book" }).click(); await expect(page.getByRole("heading", { name: "Mistake Book" })).toBeVisible(); await expect(page.locator(".mistake-card").first()).toBeVisible();
  await page.goto("/"); await page.getByRole("button", { name: "PRACTICE AGAIN" }).click(); await expect(page.locator(".progress-track")).toBeVisible();
});
