import { describe, expect, it } from "vitest";
import { wordConcepts } from "../src/content/words";
import { checkQuestionSequence } from "../src/engine/antiPattern";
import { createProgress } from "../src/engine/mastery";
import { buildSessionPlan, createDelayedRetry } from "../src/engine/sessionBuilder";
import { approvedVisualsFor } from "../src/content/visualManifest";
import { createQuestion } from "../src/engine/questionFactory";
import { SeededRandom } from "../src/engine/random";
describe("session anti-pattern rules",()=>{const assignment={newConceptIds:wordConcepts.slice(20,30).map((item)=>item.id),reviewConceptIds:wordConcepts.slice(30,45).map((item)=>item.id)};it("is seeded, delays first tests after learn cards, and respects anti-pattern rules",()=>{const plan=buildSessionPlan(assignment,assignment.reviewConceptIds.map(createProgress),"qa-seed-2026");expect(plan.interactions.filter((item)=>"kind" in item)).toHaveLength(10);expect(plan.questions).toHaveLength(35);expect(checkQuestionSequence(plan.questions)).toEqual([]);for(const conceptId of assignment.newConceptIds){const learnIndex=plan.interactions.findIndex((item)=>"kind" in item&&item.conceptId===conceptId);const firstQuestionIndex=plan.interactions.findIndex((item)=>!("kind" in item)&&item.targetConceptId===conceptId);const between=plan.interactions.slice(learnIndex+1,firstQuestionIndex).filter((item)=>!("kind" in item));expect(between.length).toBeGreaterThanOrEqual(4);}expect(buildSessionPlan(assignment,assignment.reviewConceptIds.map(createProgress),"qa-seed-2026").questions.map((item)=>item.id)).toEqual(plan.questions.map((item)=>item.id));const positions=plan.questions.slice(-8).map((item)=>item.correctOptionIndex);expect(new Set(positions).size).toBeGreaterThan(1);});it("uses a different approved visual and records an image for every picture option",()=>{const visuals=approvedVisualsFor("colour-red");expect(visuals.length).toBeGreaterThan(2);const question=createQuestion("colour-red","WORD_TO_PICTURE",new SeededRandom("variant-rotation"),[visuals[0]!.id]);expect(question.visualAssetId).not.toBe(visuals[0]!.id);expect(Object.keys(question.optionVisualAssetIds??{})).toEqual(expect.arrayContaining(question.options));});it("will not make a wrong answer reappear before a five-question delay",()=>{const plan=buildSessionPlan(assignment,[],"retry-seed");const id=plan.questions[0]!.targetConceptId;expect(createDelayedRetry(id,4,"retry-seed",plan.questions.slice(0,4))).toBeUndefined();const retry=createDelayedRetry(id,5,"retry-seed",plan.questions.slice(0,6));expect(retry?.isRetry).toBe(true);});});
