import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { conceptDimensions, dailyRows, durationMinutes, metric } from "../analytics/teacherDashboard";
import { streak, weakConcepts } from "../analytics/teacherMetrics";
import { catalogById } from "../content/catalog";
import { IndexedDbProgressRepository } from "../storage/progressRepository";
import type { ConceptProgress, SessionRecord } from "../types/learning";

const repository = new IndexedDbProgressRepository();

export function SimpleTeacherPage() {
  const navigate = useNavigate(); const [sessions, setSessions] = useState<SessionRecord[]>([]); const [progress, setProgress] = useState<ConceptProgress[]>([]); const [attempts, setAttempts] = useState<Awaited<ReturnType<typeof repository.getAttempts>>>([]); const [selected, setSelected] = useState<string>();
  useEffect(() => { void (async () => { setSessions(await repository.getSessions()); setProgress(await repository.getAllConceptProgress()); setAttempts(await repository.getAttempts()); })(); }, []);
  const todayKey = new Date().toISOString().slice(0, 10); const today = sessions.find((item) => (item.kind ?? "daily") === "daily" && item.startedAt.slice(0, 10) === todayKey); const todayAttempts = attempts.filter((item) => item.createdAt.slice(0, 10) === todayKey); const listening = conceptDimensions(todayAttempts).listening; const reading = conceptDimensions(todayAttempts).wordReading; const weak = weakConcepts(attempts, progress).slice(0, 8); const rows = dailyRows(sessions, attempts, 7);
  const detail = selected ? catalogById.get(selected) : undefined;
  if (detail) { const record = progress.find((item) => item.conceptId === detail.id); const wordAttempts = attempts.filter((item) => item.conceptId === detail.id); const summary = metric(wordAttempts); return <main className="teacher-page"><button className="back-button" onClick={() => setSelected(undefined)}>← Teacher</button><h1>{detail.display}</h1><section className="teacher-summary"><article><b>{summary.attempts}</b><span>Attempts</span></article><article><b>{summary.attempts - summary.correct}</b><span>Mistakes</span></article><article><b>{Math.round(summary.accuracy * 100)}%</b><span>Accuracy</span></article><article><b>{record?.status ?? "new"}</b><span>Status</span></article></section><section><h2>Mastery</h2><p>Picture {record?.mastery.pictureMeaning ?? 0} · Listening {record?.mastery.listeningMeaning ?? 0} · Reading {record?.mastery.wordReading ?? 0} · Phrase {record?.mastery.phraseUnderstanding ?? 0} · Sentence {record?.mastery.sentenceUnderstanding ?? 0}</p><p>Last reviewed: {record?.lastReviewedAt?.slice(0, 10) ?? "—"}</p></section></main>; }
  return <main className="teacher-page"><button className="back-button" onClick={() => navigate("/")}>← Back to Kimi</button><h1>Teacher</h1><section className="teacher-summary"><article><b>{today?.completedAt ? "Completed" : "Not completed"}</b><span>Today</span></article><article><b>{today?.completedAt ? `${durationMinutes(today)} min` : "—"}</b><span>Study time</span></article><article><b>{Math.round(metric(todayAttempts).accuracy * 100)}%</b><span>Accuracy</span></article><article><b>{Math.round(listening.accuracy * 100)}%</b><span>Listening</span></article><article><b>{Math.round(reading.accuracy * 100)}%</b><span>Word Reading</span></article><article><b>{streak(sessions)}</b><span>Current streak</span></article></section><section><h2>Weak Words</h2>{weak.length ? <table><thead><tr><th>Word</th><th>Mistakes</th><th>Accuracy</th><th>Status</th></tr></thead><tbody>{weak.map((item) => { const record = progress.find((entry) => entry.conceptId === item.conceptId); return <tr key={item.conceptId} onClick={() => setSelected(item.conceptId)}><td>{item.display}</td><td>{item.attempts - Math.round(item.attempts * item.accuracy)}</td><td>{Math.round(item.accuracy * 100)}%</td><td>{record?.status ?? "new"}</td></tr>; })}</tbody></table> : <p>No weak words yet.</p>}</section><section><h2>Recent 7 Days</h2><div className="day-table">{rows.map((row) => <div key={row.date}><b>{row.date.slice(5)}</b><span>{row.completed ? "✓" : "—"}</span><small>{row.duration} min · {Math.round(row.accuracy * 100)}%</small></div>)}</div></section></main>;
}
