import type { QuestionCapabilities, WordConcept } from "../types/learning";

const all: QuestionCapabilities = { wordToPicture: true, audioToPicture: true, pictureToWord: true, audioToWord: true, phrase: true, sentence: true };
const audioOnly: QuestionCapabilities = { wordToPicture: false, audioToPicture: false, pictureToWord: false, audioToWord: true, phrase: true, sentence: true };
const row = (id: string, display: string, meaningKey: string, category: string, lesson: number, status: WordConcept["curriculumStatus"] = "core", kind: WordConcept["kind"] = "word", capabilities = all): WordConcept => ({
  id, display, meaningKey, category, kind, sourceLessons: [lesson], curriculumStatus: status, enabledByDefault: status === "core",
  forms: kind === "word" && category === "objects" ? { singular: display, plural: `${display}s` } : undefined,
  audio: { word: undefined, phraseIds: [], sentenceIds: [] }, visuals: { core: [], variants: [], scenes: [] }, capabilities, distractorPool: [], phraseIds: [], sentenceIds: [],
});

export const wordConcepts: WordConcept[] = [
  row("greeting-hello", "hello", "greeting hello", "greetings", 1, "core", "word", audioOnly), row("greeting-hi", "hi", "greeting hi", "greetings", 1, "core", "word", audioOnly), row("greeting-goodbye", "goodbye", "farewell", "greetings", 1, "core", "word", audioOnly),
  row("person-boy", "boy", "boy", "people", 1), row("person-girl", "girl", "girl", "people", 1), row("feeling-happy", "happy", "happy", "feelings", 1), row("feeling-sad", "sad", "sad", "feelings", 1), row("feeling-tired", "tired", "tired", "feelings", 1),
  row("action-stand-up", "stand up", "stand up", "classroom-actions", 1, "core", "chunk"), row("action-sit-down", "sit down", "sit down", "classroom-actions", 1, "core", "chunk"), row("action-look", "look", "look", "classroom-actions", 1), row("action-listen", "listen", "listen", "classroom-actions", 1), row("action-point", "point", "point", "classroom-actions", 1), row("action-touch", "touch", "touch", "classroom-actions", 1), row("action-show-me", "show me", "show/show me", "classroom-actions", 1, "core", "chunk"), row("action-give", "give", "give", "classroom-actions", 1), row("action-take", "take", "take", "classroom-actions", 1), row("action-come-here", "come here", "come here", "classroom-actions", 1, "core", "chunk"), row("action-stop", "stop", "stop", "classroom-actions", 1), row("action-go", "go", "go", "classroom-actions", 1),
  row("colour-red", "red", "red colour", "colours", 1), row("colour-blue", "blue", "blue colour", "colours", 1), row("colour-yellow", "yellow", "yellow colour", "colours", 1), row("colour-green", "green", "green colour", "colours", 1), row("colour-orange", "orange", "orange colour", "colours", 2), row("colour-pink", "pink", "pink colour", "colours", 2), row("colour-purple", "purple", "purple colour", "colours", 2), row("colour-black", "black", "black colour", "colours", 2), row("colour-white", "white", "white colour", "colours", 2), row("colour-brown", "brown", "brown colour", "colours", 2),
  ...([["01","one",1,"core"],["02","two",1,"core"],["03","three",1,"core"],["04","four",1,"core"],["05","five",1,"core"],["06","six",1,"core"],["07","seven",3,"core"],["08","eight",3,"exposure"],["09","nine",3,"exposure"],["10","ten",3,"exposure"],["11","eleven",3,"bonus"],["12","twelve",3,"bonus"],["13","thirteen",3,"bonus"],["14","fourteen",3,"bonus"],["15","fifteen",3,"bonus"],["16","sixteen",3,"bonus"],["17","seventeen",3,"bonus"],["18","eighteen",3,"bonus"],["19","nineteen",3,"bonus"],["20","twenty",3,"bonus"]] as const).map(([number, display, lesson, status]) => row(`number-${number}`, display, `number ${Number(number)}`, "numbers", lesson, status)),
  row("object-ball", "ball", "ball", "objects", 1), row("object-table", "table", "table", "objects", 1), row("object-chair", "chair", "chair", "objects", 1), row("object-pencil", "pencil", "pencil", "objects", 2), row("object-star", "star", "star", "objects", 2), row("object-apple", "apple", "apple", "objects", 2), row("object-bag", "bag", "bag", "objects", 2), row("object-banana", "banana", "banana", "objects", 3), row("object-orange-fruit", "orange", "orange fruit", "objects", 3), row("object-cookie", "cookie", "cookie", "objects", 3), row("object-crayon", "crayon", "crayon", "objects", 3), row("object-book", "book", "book", "objects", 3), row("object-notebook", "notebook", "notebook", "objects", 3), row("object-eraser", "eraser", "eraser", "objects", 3), row("object-ruler", "ruler", "ruler", "objects", 3), row("object-toy-car", "toy car", "toy car", "objects", 3, "core", "multiword-noun"), row("object-teddy-bear", "teddy bear", "teddy bear", "objects", 3, "core", "multiword-noun"), row("object-basket", "basket", "basket", "objects", 3), row("object-euro", "euro", "euro", "objects", 3),
];

const groups = [["colour-red","colour-blue","colour-yellow","colour-green","colour-pink","colour-purple","colour-orange"],["object-apple","object-banana","object-orange-fruit","object-cookie"],["action-point","action-touch","action-look","action-show-me"],["number-01","number-02","number-03","number-04","number-05","number-06","number-07"]];
for (const concept of wordConcepts) {
  const group = groups.find((items) => items.includes(concept.id)) ?? wordConcepts.filter((item) => item.category === concept.category).map((item) => item.id);
  concept.distractorPool = group.filter((id) => id !== concept.id && !(["colour-orange", "object-orange-fruit"] as string[]).includes(id));
}
export const conceptById = new Map(wordConcepts.map((concept) => [concept.id, concept]));
