import { conceptById } from "../content/words";
import type { AttemptEvent, ConceptProgress, QuestionType, SessionRecord } from "../types/learning";
export interface WeakConcept { conceptId: string; display: string; attempts: number; accuracy: number; nextReviewAt?: string; }
const questionTypeBuckets: Record<"listening" | "reading" | "phrase" | "sentence", QuestionType[]> = { listening:["AUDIO_TO_PICTURE","AUDIO_TO_WORD"], reading:["PICTURE_TO_WORD"], phrase:["PHRASE_MATCH"], sentence:["SENTENCE_MATCH"] };
const typesFor = (bucket: "listening" | "reading" | "phrase" | "sentence"): QuestionType[] => questionTypeBuckets[bucket];
export function accuracy(attempts: AttemptEvent[], types?: QuestionType[]) { const source = types ? attempts.filter((attempt) => types.includes(attempt.questionType)) : attempts; return source.length ? source.filter((attempt) => attempt.correct).length / source.length : 0; }
export function skillBreakdown(attempts: AttemptEvent[]) { return { listening: accuracy(attempts, typesFor("listening")), reading: accuracy(attempts, typesFor("reading")), pictureMeaning: accuracy(attempts, ["WORD_TO_PICTURE","AUDIO_TO_PICTURE"]), phrase: accuracy(attempts, typesFor("phrase")), sentence: accuracy(attempts, typesFor("sentence")) }; }
export function weakConcepts(attempts: AttemptEvent[], progress: ConceptProgress[]): WeakConcept[] { const byProgress = new Map(progress.map((item) => [item.conceptId,item])); return [...new Set(attempts.map((item) => item.conceptId))].map((conceptId) => { const events=attempts.filter((item)=>item.conceptId===conceptId); return { conceptId, display: conceptById.get(conceptId)?.display ?? conceptId, attempts: events.length, accuracy: accuracy(events), nextReviewAt: byProgress.get(conceptId)?.nextReviewAt }; }).sort((a,b)=>a.accuracy-b.accuracy || b.attempts-a.attempts); }
export function dailyCompletion(sessions: SessionRecord[]) { return sessions.filter((session) => (session.kind ?? "daily") === "daily" && Boolean(session.completedAt) && session.targetConceptIds.length > 0); }
export function streak(sessions: SessionRecord[]) { const dates=[...new Set(dailyCompletion(sessions).map((session)=>session.completedAt!.slice(0,10)))].sort().reverse(); let total=0; let cursor=new Date(); cursor.setUTCHours(0,0,0,0); for(const date of dates){if(date===cursor.toISOString().slice(0,10)){total++;cursor.setUTCDate(cursor.getUTCDate()-1)}else if(total===0){continue}else break;} return total; }
